modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "All rights reserved."

[[mods]]
modId = "quasar_client"
version = "${version}"
displayName = "Quasar Client Companion"
authors = "anar4732"
description = '''
An optional client-side mod that provides various quality-of-life features and enhancements for CDU players.
'''
logoFile = "assets/quasar_client/icon.png"
displayTest = "NONE"

[[dependencies.quasar_client]]
modId = "neoforge"
mandatory = true
versionRange = "1"
ordering = "NONE"
side = "BOTH"

[[dependencies.quasar_client]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quasar_client]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "quasar_client.mixins.json"